-- MySQL Script generated by MySQL Workbench
-- 12/22/14 07:00:56
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema petPamonha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petPamonha` DEFAULT CHARACTER SET utf8 ;
USE `petPamonha` ;

-- -----------------------------------------------------
-- Table `petPamonha`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petPamonha`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(70) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `Telefone` VARCHAR(14) NOT NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petPamonha`.`Pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petPamonha`.`Pet` (
  `idPet` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `dataDeNascimento` DATE NOT NULL,
  `rga` VARCHAR(7) NOT NULL,
  `raca` VARCHAR(45) NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idPet`, `idCliente`),
  INDEX `fk_Pet_Cliente_idx` (`idCliente` ASC),
  UNIQUE INDEX `rga_UNIQUE` (`rga` ASC),
  CONSTRAINT `fk_Pet_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `petPamonha`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petPamonha`.`Tratamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petPamonha`.`Tratamento` (
  `idTratamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `duracaoMedia` TIME NOT NULL,
  PRIMARY KEY (`idTratamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petPamonha`.`petTratamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petPamonha`.`petTratamento` (
  `idPet` INT NOT NULL,
  `idTratamento` INT NOT NULL,
  `dataHora` DATETIME NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT false,
  PRIMARY KEY (`idPet`, `idTratamento`),
  INDEX `fk_Pet_has_Tratamento_Tratamento1_idx` (`idTratamento` ASC),
  INDEX `fk_Pet_has_Tratamento_Pet1_idx` (`idPet` ASC),
  CONSTRAINT `fk_Pet_has_Tratamento_Pet1`
    FOREIGN KEY (`idPet`)
    REFERENCES `petPamonha`.`Pet` (`idPet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pet_has_Tratamento_Tratamento1`
    FOREIGN KEY (`idTratamento`)
    REFERENCES `petPamonha`.`Tratamento` (`idTratamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
